"""
ai_report_generator.py
========================
AI Report Generator for JusticeLens AI.

Orchestrates every other generator in this package (Executive Summary,
District Comparison, Policy Recommendation Engine, and the model
comparison leaderboard from ``model_training.py`` /
``model_evaluation.py``) into a single, saved Markdown report -- the
document a DoJ/NALSA official could actually download and read end to
end.

Each section is generated independently and defensively: if one section's
Granite call fails, that section falls back to its own deterministic
template (as implemented in the underlying generator) rather than
aborting the whole report. Every section's provenance
(``is_ai_generated``) is recorded and surfaced in the report's appendix,
so a reader can see exactly which parts were AI-narrated versus
template-generated.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

from justicelens import config, prompt_templates
from justicelens.district_comparison import DistrictComparisonGenerator
from justicelens.executive_summary_generator import ExecutiveSummaryGenerator
from justicelens.logger import get_logger
from justicelens.policy_recommendation_engine import PolicyRecommendationEngine
from justicelens.utils import NarrativeGenerationError, ensure_dir
from justicelens.watsonx_integration import GraniteClient, NarrativeResult

logger = get_logger(__name__)


class AIReportGenerator:
    """Assembles a complete, multi-section Markdown disparity report.

    Typical usage::

        report_generator = AIReportGenerator()
        report_path, sections = report_generator.generate_full_report(
            scope_label="All India",
            predictions_df=predictions_df,
            global_top_drivers=importance_df,
            comparison_table=artifacts.comparison_table,
            best_model_name=artifacts.best_result.model_name,
            top_n_districts_for_recommendations=3,
        )
    """

    def __init__(self, client: Optional[GraniteClient] = None) -> None:
        """Initialize the report generator and the sub-generators it
        orchestrates, all sharing one ``GraniteClient`` instance (so the
        IAM token is only fetched/cached once per report run).

        Args:
            client: A ``GraniteClient`` instance. Defaults to a new
                client constructed from environment configuration.
        """
        self.client = client or GraniteClient()
        self.executive_summary_generator = ExecutiveSummaryGenerator(self.client)
        self.district_comparison_generator = DistrictComparisonGenerator(self.client)
        self.policy_recommendation_engine = PolicyRecommendationEngine(self.client)

    def _generate_methodology_section(self, best_model_name: str) -> str:
        """Produce the static "Methodology" section. This section is
        deliberately NOT sent to Granite: it describes the fixed pipeline
        architecture rather than data that varies run to run, so a
        deterministic, hand-authored description is both cheaper and more
        reliable than narrating it.

        Args:
            best_model_name: Name of the model selected as best for this
                run, referenced in the description.

        Returns:
            A Markdown-formatted methodology section body.
        """
        return (
            "This report is generated by JusticeLens AI, an AI decision "
            "-support pipeline analyzing district-wise Tele-Law case "
            "registration data (data.gov.in, FY 2021-22 to FY 2024-25) "
            "alongside district-level demographic indicators. The "
            "pipeline: (1) ingests and validates the official dataset, "
            "with a deterministic synthetic fallback if live retrieval "
            "fails; (2) harmonizes schema drift across fiscal years and "
            "reconciles district names against the demographic dataset; "
            "(3) engineers per-capita, advice-ratio, growth, and "
            "rural-penetration features; (4) trains and compares five "
            "classification models (Logistic Regression, Decision Tree, "
            f"Random Forest, Gradient Boosting, and XGBoost), selecting "
            f"**{best_model_name}** as the best performer by cross"
            "-validated ROC-AUC; and (5) explains every prediction using "
            "SHAP (SHapley Additive exPlanations). The narrative sections "
            "of this report are produced by IBM Granite (via IBM "
            "watsonx.ai) strictly from these precomputed, auditable "
            "figures -- the generative layer narrates results, it does "
            "not calculate them."
        )

    def generate_full_report(
        self,
        scope_label: str,
        predictions_df: pd.DataFrame,
        global_top_drivers: pd.DataFrame,
        comparison_table: pd.DataFrame,
        best_model_name: str,
        top_n_districts_for_recommendations: int = 3,
        district_records_with_explanations: Optional[List[Dict[str, object]]] = None,
        output_path: Optional[Path] = None,
    ) -> "AIReportResult":
        """Generate and save the complete multi-section Markdown report.

        Args:
            scope_label: Label for the report's overall scope (e.g.
                "All India -- FY 2021-22 to FY 2024-25").
            predictions_df: Dataframe of district-year records with model
                predictions attached (columns: ``state_name``,
                ``district_name``, ``predicted_class``,
                ``predicted_probability``, plus feature columns).
            global_top_drivers: Global feature importance dataframe from
                ``shap_explainability.SHAPExplainer.compute_feature_importance``.
            comparison_table: Model comparison leaderboard dataframe from
                ``model_training``/``model_evaluation``.
            best_model_name: Name of the selected best model.
            top_n_districts_for_recommendations: How many of the worst
                -affected districts get their own policy recommendation
                subsection.
            district_records_with_explanations: Optional pre-built list of
                per-district dicts (each with ``district_name``,
                ``state_name``, ``predicted_class``,
                ``predicted_probability``, and
                ``top_contributing_features``) used for both the district
                -comparison section and per-district recommendations. If
                omitted, only the executive summary, model performance,
                and methodology sections are generated (comparison/
                recommendation sections are skipped).
            output_path: Destination ``.md`` file path. Defaults to
                ``config.OUTPUT_DIR / "reports" / "justicelens_report_<timestamp>.md"``.

        Returns:
            An :class:`AIReportResult` bundling the saved file path and
            every section's :class:`~justicelens.watsonx_integration.NarrativeResult`
            for audit/governance purposes.

        Raises:
            NarrativeGenerationError: Propagated from any required
                sub-generator if its input data is malformed.
        """
        logger.info("=== AI Report Generator: START (scope='%s') ===", scope_label)
        section_results: Dict[str, NarrativeResult] = {}

        executive_summary = self.executive_summary_generator.generate(
            scope_label=scope_label,
            predictions_df=predictions_df,
            global_top_drivers=global_top_drivers,
        )
        section_results["executive_summary"] = executive_summary

        model_performance_data = prompt_templates.build_model_performance_section_data(
            comparison_table_rows=comparison_table.to_dict("records"),
            best_model_name=best_model_name,
        )
        model_performance_prompt = prompt_templates.build_ai_report_section_prompt(
            section_title="Model Performance Summary",
            section_purpose=(
                "Explain, for a non-technical policymaker, how well the "
                "disparity classification model performs and why the "
                "selected model was chosen."
            ),
            supporting_data_block=model_performance_data,
        )
        model_performance_generation = self.client.generate_safe(model_performance_prompt)
        if model_performance_generation is not None:
            model_performance_result = NarrativeResult(
                narrative_text=model_performance_generation.text,
                is_ai_generated=True,
                model_id=model_performance_generation.model_id,
                latency_seconds=model_performance_generation.latency_seconds,
                source_data={"comparison_table": comparison_table.to_dict("records")},
            )
        else:
            model_performance_result = NarrativeResult(
                narrative_text=(
                    f"The best-performing model, **{best_model_name}**, was "
                    f"selected from five candidates (Logistic Regression, "
                    f"Decision Tree, Random Forest, Gradient Boosting, "
                    f"XGBoost) based on cross-validated ROC-AUC. Full "
                    f"comparison metrics are in the table below.\n\n"
                    f"[Note: generated by deterministic template; "
                    f"watsonx.ai was unavailable.]"
                ),
                is_ai_generated=False,
                model_id="template_fallback",
                source_data={"comparison_table": comparison_table.to_dict("records")},
            )
        section_results["model_performance"] = model_performance_result

        comparison_result: Optional[NarrativeResult] = None
        recommendation_results: List[Dict[str, object]] = []

        if district_records_with_explanations and len(
            district_records_with_explanations
        ) >= 2:
            comparison_result = self.district_comparison_generator.compare(
                district_records_with_explanations
            )
            section_results["district_comparison"] = comparison_result

            worst_districts = sorted(
                district_records_with_explanations,
                key=lambda r: r["predicted_probability"],
                reverse=True,
            )[:top_n_districts_for_recommendations]

            for record in worst_districts:
                rec_result = self.policy_recommendation_engine.generate(
                    district_name=record["district_name"],
                    state_name=record["state_name"],
                    predicted_class=record["predicted_class"],
                    predicted_probability=record["predicted_probability"],
                    top_contributing_features=record["top_contributing_features"],
                )
                recommendation_results.append(
                    {
                        "district_name": record["district_name"],
                        "state_name": record["state_name"],
                        "result": rec_result,
                    }
                )
                section_results[
                    f"policy_recommendation_{record['district_name']}"
                ] = rec_result

        methodology_text = self._generate_methodology_section(best_model_name)

        report_markdown = self._assemble_markdown(
            scope_label=scope_label,
            executive_summary=executive_summary,
            model_performance=model_performance_result,
            comparison_table=comparison_table,
            comparison_result=comparison_result,
            recommendation_results=recommendation_results,
            methodology_text=methodology_text,
            section_results=section_results,
        )

        destination = output_path or (
            config.OUTPUT_DIR
            / "reports"
            / f"justicelens_report_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.md"
        )
        ensure_dir(destination.parent)
        destination.write_text(report_markdown, encoding="utf-8")
        logger.info(
            "=== AI Report Generator: COMPLETE. Saved report to %s (%d "
            "section(s), %d AI-generated) ===",
            destination,
            len(section_results),
            sum(1 for r in section_results.values() if r.is_ai_generated),
        )

        return AIReportResult(
            report_path=destination,
            section_results=section_results,
        )

    def _render_table_markdown(self, df: pd.DataFrame) -> str:
        """Render a dataframe as a Markdown table, falling back to a
        plain-text table if the optional ``tabulate`` dependency (required
        by ``DataFrame.to_markdown``) is not installed.

        Args:
            df: Dataframe to render.

        Returns:
            A Markdown (or, on fallback, monospace plain-text) table
            string.
        """
        try:
            return df.to_markdown(index=False)
        except ImportError:
            logger.warning(
                "'tabulate' package not installed; rendering comparison "
                "table as plain text instead of a Markdown table."
            )
            return "```\n" + df.to_string(index=False) + "\n```"

    def _assemble_markdown(
        self,
        scope_label: str,
        executive_summary: NarrativeResult,
        model_performance: NarrativeResult,
        comparison_table: pd.DataFrame,
        comparison_result: Optional[NarrativeResult],
        recommendation_results: List[Dict[str, object]],
        methodology_text: str,
        section_results: Dict[str, NarrativeResult],
    ) -> str:
        """Render every generated section into one Markdown document.

        Args:
            scope_label: Overall report scope label.
            executive_summary: Executive summary section result.
            model_performance: Model performance section result.
            comparison_table: Model leaderboard dataframe (rendered as a
                Markdown table in an appendix).
            comparison_result: Optional district comparison section
                result.
            recommendation_results: List of per-district recommendation
                results.
            methodology_text: Static methodology section body.
            section_results: All section results, used to build the
                provenance appendix.

        Returns:
            The complete Markdown document as a string.
        """
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        parts = [
            "# JusticeLens AI -- Tele-Law Disparity Report",
            f"**Scope:** {scope_label}  \n**Generated:** {generated_at}",
            "",
            "## Executive Summary",
            executive_summary.narrative_text,
            "",
            "## Model Performance Summary",
            model_performance.narrative_text,
            "",
            "### Model Comparison Leaderboard",
            self._render_table_markdown(comparison_table),
        ]

        if comparison_result is not None:
            parts += ["", "## District Comparison", comparison_result.narrative_text]

        if recommendation_results:
            parts += ["", "## Priority District Policy Recommendations"]
            for item in recommendation_results:
                parts += [
                    f"### {item['district_name']}, {item['state_name']}",
                    item["result"].narrative_text,
                ]

        parts += ["", "## Methodology", methodology_text]

        provenance_lines = ["| Section | Source | Model |", "|---|---|---|"]
        for name, result in section_results.items():
            source = "IBM Granite (watsonx.ai)" if result.is_ai_generated else "Deterministic template"
            provenance_lines.append(f"| {name} | {source} | {result.model_id} |")
        parts += ["", "## Report Provenance (Audit Trail)", "\n".join(provenance_lines)]

        parts += [
            "",
            "*This report was generated by JusticeLens AI. All figures "
            "are derived from official/synthetic Tele-Law data processed "
            "through a validated ML + SHAP pipeline; narrative sections "
            "marked 'IBM Granite' in the provenance table above were "
            "AI-generated strictly from those figures, and sections "
            "marked 'Deterministic template' were produced without any "
            "AI model when watsonx.ai was unavailable.*",
        ]

        return "\n\n".join(parts)


class AIReportResult:
    """Result of a full report generation run.

    Attributes:
        report_path: Path to the saved Markdown report file.
        section_results: Dict mapping section name -> the
            ``NarrativeResult`` that produced it, for audit/governance
            purposes.
    """

    def __init__(
        self, report_path: Path, section_results: Dict[str, NarrativeResult]
    ) -> None:
        self.report_path = report_path
        self.section_results = section_results

    @property
    def ai_generated_section_count(self) -> int:
        """Number of sections actually produced by a live Granite call
        (as opposed to the deterministic template fallback)."""
        return sum(1 for r in self.section_results.values() if r.is_ai_generated)

    @property
    def total_section_count(self) -> int:
        """Total number of sections in the report."""
        return len(self.section_results)
