"""
district_comparison.py
========================
District Comparison Generator for JusticeLens AI.

Produces a natural-language, side-by-side comparison of two or more
districts' Tele-Law disparity profiles, grounded in each district's model
prediction and SHAP-derived top contributing factors. As with every other
generator in this package, it prefers IBM Granite (via
``watsonx_integration.GraniteClient``) and falls back to a deterministic,
rule-based comparison built from the same structured data when watsonx.ai
is unavailable.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from justicelens import prompt_templates
from justicelens.logger import get_logger
from justicelens.utils import NarrativeGenerationError
from justicelens.watsonx_integration import GraniteClient, NarrativeResult

logger = get_logger(__name__)

#: Fields every district record passed to this generator must contain.
_REQUIRED_FIELDS = [
    "district_name",
    "state_name",
    "fiscal_year",
    "predicted_class",
    "predicted_probability",
    "cases_per_lakh_population",
    "advice_enabled_ratio",
]


class DistrictComparisonGenerator:
    """Generates structured natural-language comparisons across 2+
    districts.

    Typical usage::

        generator = DistrictComparisonGenerator()
        result = generator.compare([district_a_record, district_b_record])
        print(result.narrative_text)
    """

    def __init__(self, client: Optional[GraniteClient] = None) -> None:
        """Initialize the generator.

        Args:
            client: A ``GraniteClient`` instance. Defaults to a new
                client constructed from environment configuration.
        """
        self.client = client or GraniteClient()

    def _validate_records(self, district_records: List[Dict[str, object]]) -> None:
        """Validate that every district record has the required fields.

        Args:
            district_records: Records to validate.

        Raises:
            NarrativeGenerationError: If fewer than 2 records are given,
                or any record is missing a required field.
        """
        if len(district_records) < 2:
            raise NarrativeGenerationError(
                f"District comparison requires at least 2 district "
                f"records, got {len(district_records)}."
            )
        for i, record in enumerate(district_records):
            missing = [f for f in _REQUIRED_FIELDS if f not in record]
            if missing:
                raise NarrativeGenerationError(
                    f"District record at index {i} is missing required "
                    f"field(s): {missing}"
                )

    def _build_fallback_narrative(self, district_records: List[Dict[str, object]]) -> str:
        """Build a deterministic, rule-based comparison narrative when
        Granite is unavailable.

        Args:
            district_records: Validated district records.

        Returns:
            A plain-language comparison string.
        """
        ranked = sorted(
            district_records, key=lambda r: r["predicted_probability"], reverse=True
        )

        lines = ["District Comparison\n"]
        for record in ranked:
            lines.append(
                f"- {record['district_name']}, {record['state_name']} "
                f"(FY {record['fiscal_year']}): "
                f"{record['predicted_class']} "
                f"({record['predicted_probability']:.1%} underserved "
                f"probability); "
                f"{record['cases_per_lakh_population']:.1f} cases per lakh "
                f"population; "
                f"{record['advice_enabled_ratio']:.1%} advice-enabled ratio."
            )

        ranking_text = " > ".join(r["district_name"] for r in ranked)
        lines.append(
            f"\nRanked from highest to lowest underserved risk: {ranking_text}."
        )
        lines.append(
            "\n[Note: This comparison was generated by a deterministic "
            "template because the IBM watsonx.ai Granite narration "
            "service was unavailable at generation time. All figures "
            "above are drawn directly from the underlying model outputs.]"
        )
        return "\n".join(lines)

    def compare(self, district_records: List[Dict[str, object]]) -> NarrativeResult:
        """Generate a natural-language comparison across the given
        district records.

        Args:
            district_records: List of 2 or more dicts, each describing
                one district-year record. Required keys: ``district_name``,
                ``state_name``, ``fiscal_year``, ``predicted_class``,
                ``predicted_probability``, ``cases_per_lakh_population``,
                ``advice_enabled_ratio``. Optionally include
                ``top_contributing_features`` (list of dicts as produced
                by ``shap_explainability.SHAPExplainer.explain_prediction``)
                for a richer comparison.

        Returns:
            A :class:`NarrativeResult`.

        Raises:
            NarrativeGenerationError: If fewer than 2 records are given or
                any record is missing required fields.
        """
        self._validate_records(district_records)

        prompt = prompt_templates.build_district_comparison_prompt(district_records)
        generation = self.client.generate_safe(prompt)

        source_data = {"districts": district_records}

        if generation is not None:
            logger.info(
                "District comparison generated via Granite for %d districts",
                len(district_records),
            )
            return NarrativeResult(
                narrative_text=generation.text,
                is_ai_generated=True,
                model_id=generation.model_id,
                latency_seconds=generation.latency_seconds,
                source_data=source_data,
            )

        logger.info(
            "District comparison falling back to template for %d districts",
            len(district_records),
        )
        fallback_text = self._build_fallback_narrative(district_records)
        return NarrativeResult(
            narrative_text=fallback_text,
            is_ai_generated=False,
            model_id="template_fallback",
            latency_seconds=0.0,
            source_data=source_data,
        )
