"""
api/main.py
============
FastAPI backend for JusticeLens AI.

Loads the pre-trained model and prediction dataset (generated by the orchestrator)
and exposes REST endpoints for the frontend.

Deploy this as an IBM Code Engine App.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
import joblib
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict, Any, Optional

from justicelens import config
from justicelens.logger import get_logger
from justicelens.shap_explainability import SHAPExplainer

logger = get_logger(__name__)

# --- FastAPI App Setup ---
app = FastAPI(title="JusticeLens AI API", version="1.0")

# Enable CORS for frontend (deployed anywhere)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict to your frontend domain in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Global Variables (Loaded at Startup) ---
model_bundle = None
predictions_df = None
feature_names = None
class_names = config.ML_CLASS_NAMES
shap_explainer = None

# --- Request/Response Models ---
class PredictRequest(BaseModel):
    features: Dict[str, float]

class PredictResponse(BaseModel):
    predicted_class: str
    predicted_probability: float
    shap_values: Optional[List[Dict[str, Any]]] = None

# --- Startup Event ---
@app.on_event("startup")
async def load_artifacts():
    global model_bundle, predictions_df, feature_names, shap_explainer
    
    logger.info("🚀 JusticeLens API starting up...")
    
    # 1. Load Model
    model_path = config.MODEL_DIR / config.ML_BEST_MODEL_FILENAME
    if not model_path.exists():
        logger.error(f"Model not found at {model_path}. Run the orchestrator first.")
        raise RuntimeError("Model artifacts missing.")
    
    model_bundle = joblib.load(model_path)
    feature_names = model_bundle["feature_names"]
    logger.info(f"✅ Model loaded: {model_bundle['model_name']}")

    # 2. Load Predictions Dataset
    pred_path = config.DATA_PROCESSED_DIR / "predictions_all.csv"
    if not pred_path.exists():
        logger.error(f"Predictions not found at {pred_path}. Run the orchestrator first.")
        raise RuntimeError("Predictions dataset missing.")
    
    predictions_df = pd.read_csv(pred_path)
    logger.info(f"✅ Predictions loaded: {len(predictions_df)} rows")

    # 3. Load SHAP Background (Optional)
    try:
        bg_path = config.DATA_PROCESSED_DIR / "shap_background.csv"
        if bg_path.exists():
            background_data = pd.read_csv(bg_path)
            shap_explainer = SHAPExplainer(model_bundle, background_data)
            logger.info("✅ SHAP explainer loaded.")
    except Exception as e:
        logger.warning(f"SHAP explainer could not be loaded: {e}")

# --- Health Check ---
@app.get("/")
async def root():
    return {"status": "online", "model": model_bundle["model_name"] if model_bundle else "none"}

# --- Endpoints ---
@app.get("/states")
async def get_states():
    """Get list of unique states/UTs."""
    if predictions_df is None:
        raise HTTPException(503, "Data not loaded")
    return sorted(predictions_df["state_name"].unique().tolist())

@app.get("/districts/{state}")
async def get_districts(state: str):
    """Get districts for a specific state."""
    if predictions_df is None:
        raise HTTPException(503, "Data not loaded")
    df = predictions_df[predictions_df["state_name"] == state]
    return sorted(df["district_name"].unique().tolist())

@app.get("/years")
async def get_years():
    """Get available fiscal years."""
    if predictions_df is None:
        raise HTTPException(503, "Data not loaded")
    return sorted(predictions_df["fiscal_year"].unique().tolist())

@app.get("/district-data")
async def get_district_data(state: str, district: str, year: str):
    """Get full profile for a specific district-year."""
    if predictions_df is None:
        raise HTTPException(503, "Data not loaded")
    
    df = predictions_df[
        (predictions_df["state_name"] == state) &
        (predictions_df["district_name"] == district) &
        (predictions_df["fiscal_year"] == year)
    ]
    if df.empty:
        raise HTTPException(404, "Record not found")
    return df.iloc[0].to_dict()

@app.get("/executive-summary")
async def get_executive_summary(scope: str = "All India"):
    """
    Return aggregated statistics for the executive summary.
    (If you want Granite narration here, you can move the watsonx call to this API too).
    """
    if predictions_df is None:
        raise HTTPException(503, "Data not loaded")
    
    df = predictions_df if scope == "All India" else predictions_df[predictions_df["state_name"] == scope]
    
    total = len(df)
    underserved = int((df["predicted_class"] == "Underserved").sum())
    avg_prob = float(df["predicted_probability"].mean())
    
    return {
        "scope": scope,
        "total_records": total,
        "underserved_count": underserved,
        "underserved_share": underserved / max(total, 1),
        "avg_underserved_probability": avg_prob
    }

@app.post("/predict", response_model=PredictResponse)
async def predict(request: PredictRequest):
    """Score a hypothetical district."""
    if model_bundle is None:
        raise HTTPException(503, "Model not loaded")
    
    pipeline = model_bundle["pipeline"]
    
    # Create DataFrame
    input_df = pd.DataFrame([request.features])[feature_names]
    
    # Predict
    prob = float(pipeline.predict_proba(input_df)[0, 1])
    cls_idx = int(pipeline.predict(input_df)[0])
    cls_name = class_names[cls_idx]
    
    # SHAP explanation (if available)
    shap_vals = None
    if shap_explainer is not None:
        try:
            exp = shap_explainer.explain_prediction(input_df, instance_index=0)
            shap_vals = exp["top_contributing_features"]
        except Exception:
            shap_vals = []
    
    return PredictResponse(
        predicted_class=cls_name,
        predicted_probability=prob,
        shap_values=shap_vals
    )

# To run locally:
# uvicorn api.main:app --reload --port 8000